//Source code generated by AppGPT (www.appgpt.tech)

//Class to create tables and seed new database
import { DataSource } from 'typeorm';
import { DBConfiguration } from './Configuration';
import { SettingsEntity } from './db/Settings.entity';
//autogenerate imports based on resources
import { usersEntity } from './db/users.entity';
import { departmentsEntity } from './db/departments.entity';
import { initiativesEntity } from './db/initiatives.entity';
import { goalsEntity } from './db/goals.entity';
import { emissionSourcesEntity } from './db/emissionSources.entity';
import { resourceUsageEntity } from './db/resourceUsage.entity';

export class Database {
  static dbConfiguration: DBConfiguration;
  public static ds: DataSource;

  static async Initialize(dbConfiguration: DBConfiguration) {
    Database.dbConfiguration = dbConfiguration;
    let dbConfig: any = dbConfiguration as any;
    //Autogenerate entities array from resource names

    dbConfig.entities = [
      SettingsEntity,
      usersEntity,
      departmentsEntity,
      initiativesEntity,
      goalsEntity,
      emissionSourcesEntity,
      resourceUsageEntity,
    ];
    Database.ds = new DataSource(dbConfig);
    await Database.ds.initialize();

    //TODO: Drop all tables

    await Database.Seed();
  }
  static async Seed() {
    let data: any = {
      users: [
        {
          userName: 'userName 1',
          department: 1,
          password: 'password 1',
          email: 'email 1',
          id: 54,
        },
        {
          userName: 'userName 2',
          department: 2,
          password: 'password 2',
          email: 'email 2',
          id: 33,
        },
        {
          userName: 'userName 3',
          department: 3,
          password: 'password 3',
          email: 'email 3',
          id: 76,
        },
        {
          userName: 'userName 4',
          department: 4,
          password: 'password 4',
          email: 'email 4',
          id: 88,
        },
        {
          userName: 'userName 5',
          department: 5,
          password: 'password 5',
          email: 'email 5',
          id: 2,
        },
      ],
      departments: [
        { departmentName: 'departmentName 1', departmentHead: 1, id: 91 },
        { departmentName: 'departmentName 2', departmentHead: 2, id: 41 },
        { departmentName: 'departmentName 3', departmentHead: 3, id: 47 },
        { departmentName: 'departmentName 4', departmentHead: 4, id: 91 },
        { departmentName: 'departmentName 5', departmentHead: 5, id: 23 },
      ],
      initiatives: [
        {
          name: 'name 1',
          description: 'description 1',
          startDate: '2025-03-08T02:25:44.014Z',
          endDate: '2024-07-02T19:22:16.925Z',
          relatedDepartment: 1,
          status: 'status 1',
          id: 26,
        },
        {
          name: 'name 2',
          description: 'description 2',
          startDate: '2024-04-16T02:49:54.109Z',
          endDate: '2024-04-30T01:17:04.188Z',
          relatedDepartment: 2,
          status: 'status 2',
          id: 55,
        },
        {
          name: 'name 3',
          description: 'description 3',
          startDate: '2024-02-02T07:45:45.795Z',
          endDate: '2023-11-26T02:53:21.122Z',
          relatedDepartment: 3,
          status: 'status 3',
          id: 39,
        },
        {
          name: 'name 4',
          description: 'description 4',
          startDate: '2024-07-28T20:00:32.103Z',
          endDate: '2024-11-01T18:37:16.307Z',
          relatedDepartment: 4,
          status: 'status 4',
          id: 23,
        },
        {
          name: 'name 5',
          description: 'description 5',
          startDate: '2025-03-30T14:14:08.543Z',
          endDate: '2025-01-29T20:39:10.379Z',
          relatedDepartment: 5,
          status: 'status 5',
          id: 57,
        },
      ],
      goals: [
        {
          name: 'name 1',
          description: 'description 1',
          targetDate: '2025-01-08T00:06:36.533Z',
          relatedDepartment: 1,
          status: 'status 1',
          id: 51,
        },
        {
          name: 'name 2',
          description: 'description 2',
          targetDate: '2023-08-13T01:12:18.463Z',
          relatedDepartment: 2,
          status: 'status 2',
          id: 74,
        },
        {
          name: 'name 3',
          description: 'description 3',
          targetDate: '2024-07-13T11:44:43.739Z',
          relatedDepartment: 3,
          status: 'status 3',
          id: 90,
        },
        {
          name: 'name 4',
          description: 'description 4',
          targetDate: '2024-08-03T13:25:20.154Z',
          relatedDepartment: 4,
          status: 'status 4',
          id: 72,
        },
        {
          name: 'name 5',
          description: 'description 5',
          targetDate: '2023-05-15T21:10:52.691Z',
          relatedDepartment: 5,
          status: 'status 5',
          id: 79,
        },
      ],
      emissionSources: [
        {
          sourceType: 'sourceType 1',
          quantityUsed: 0.59,
          emissionFactors: 0.8,
          totalEmissions: 0.54,
          id: 26,
        },
        {
          sourceType: 'sourceType 2',
          quantityUsed: 0.45,
          emissionFactors: 0.94,
          totalEmissions: 0.48,
          id: 88,
        },
        {
          sourceType: 'sourceType 3',
          quantityUsed: 0.85,
          emissionFactors: 0.3,
          totalEmissions: 0.17,
          id: 99,
        },
        {
          sourceType: 'sourceType 4',
          quantityUsed: 0.42,
          emissionFactors: 0.92,
          totalEmissions: 0.37,
          id: 96,
        },
        {
          sourceType: 'sourceType 5',
          quantityUsed: 0.41,
          emissionFactors: 0.44,
          totalEmissions: 0.54,
          id: 90,
        },
      ],
      resourceUsage: [
        {
          resourceType: 'resourceType 1',
          quantityConsumed: 0.62,
          unitOfMeasurement: 'unitOfMeasurement 1',
          periodOfConsumption: '2023-05-16T04:49:54.042Z',
          id: 74,
        },
        {
          resourceType: 'resourceType 2',
          quantityConsumed: 0.12,
          unitOfMeasurement: 'unitOfMeasurement 2',
          periodOfConsumption: '2023-09-26T04:25:59.525Z',
          id: 41,
        },
        {
          resourceType: 'resourceType 3',
          quantityConsumed: 0.83,
          unitOfMeasurement: 'unitOfMeasurement 3',
          periodOfConsumption: '2023-07-13T10:26:12.963Z',
          id: 33,
        },
        {
          resourceType: 'resourceType 4',
          quantityConsumed: 0.55,
          unitOfMeasurement: 'unitOfMeasurement 4',
          periodOfConsumption: '2023-06-13T06:34:27.990Z',
          id: 0,
        },
        {
          resourceType: 'resourceType 5',
          quantityConsumed: 0.47,
          unitOfMeasurement: 'unitOfMeasurement 5',
          periodOfConsumption: '2025-01-20T14:15:31.443Z',
          id: 8,
        },
      ],
    };
    //Autogenerate multiple such calls ie for each resource and its data object
    let isSeeded = await this.IsSeeded();
    //if (!isSeeded) {
    //forcing app recreation
    if (true) {
      console.log('   Seeding database...');
      await this.SeedResource('usersEntity', data.users);
      await this.SeedResource('departmentsEntity', data.departments);
      await this.SeedResource('initiativesEntity', data.initiatives);
      await this.SeedResource('goalsEntity', data.goals);
      await this.SeedResource('emissionSourcesEntity', data.emissionSources);
      await this.SeedResource('resourceUsageEntity', data.resourceUsage);
      await this.SeedResource('SettingsEntity', {
        settingname: 'isSeeded',
        settingvalue: 'true',
      });
    } else {
      console.log('   Database seeded already!');
    }
  }
  static async IsSeeded() {
    const repo = Database.ds.getRepository('SettingsEntity');
    let rec: any = await repo.findOne({
      select: {
        settingname: true,
        settingvalue: true,
      },
      where: {
        settingname: 'isSeeded',
      },
    });
    if (rec && rec.settingvalue) return true;
    return false;
  }
  static async SeedResource(resourceName: any, resourceData: any) {
    const repo = Database.ds.getRepository(resourceName);
    //await repo.clear();
    console.log('   Seeding table ' + resourceName);
    await repo.upsert(resourceData, ['id']);
  }
}
